// src/modules/slider/service.ts
import { MedusaService } from "@medusajs/framework/utils"
import { Slider } from "./models/slider"

interface ISliderModuleService {
  createSliders(data: Partial<Slider> | Partial<Slider>[]): Promise<Slider[]>
  updateSliders(data: Partial<Slider> & { id: string }): Promise<Slider[]>
  deleteSliders(ids: string | string[]): Promise<void>
  listSliders(filters?: any): Promise<Slider[]>
  retrieveSlider(id: string): Promise<Slider>
}

class SliderModuleService extends MedusaService({
  Slider,
}) implements ISliderModuleService {
  // The methods are automatically generated by MedusaService
  // We don't need to implement them here
}

export default SliderModuleService